-- DSTAIRLINES.AIRCRAFT definition

CREATE TABLE `AIRCRAFT` (
  `AIRCRAFT_ID` varchar(10) NOT NULL,
  `AIRCRAFT_NAME` varchar(100) DEFAULT NULL,
  `AIRCRAFT_AIRLINE_EQUIP_CODE` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`AIRCRAFT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- DSTAIRLINES.COUNTRIES definition

CREATE TABLE `COUNTRIES` (
  `COUNTRY_ID` varchar(10) NOT NULL,
  `COUNTRY_NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`COUNTRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- DSTAIRLINES.CITIES definition

CREATE TABLE `CITIES` (
  `CITY_ID` varchar(10) NOT NULL,
  `CITY_NAME` varchar(100) DEFAULT NULL,
  `CITY_COUNTRY_FK` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`CITY_ID`),
  KEY `CITIES_FK` (`CITY_COUNTRY_FK`),
  CONSTRAINT `CITY_COUNTRY_FK` FOREIGN KEY (`CITY_COUNTRY_FK`) REFERENCES `COUNTRIES` (`COUNTRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- DSTAIRLINES.AIRLINES definition

CREATE TABLE `AIRLINES` (
  `AIRLINE_ID` varchar(10) NOT NULL,
  `AIRLINE_ICAO` varchar(10) DEFAULT NULL,
  `AIRLINE_NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`AIRLINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- DSTAIRLINES.AIRPORTS definition

CREATE TABLE `AIRPORTS` (
  `AIRPORT_ID` varchar(10) NOT NULL,
  `AIRPORT_ICAO` varchar(10) DEFAULT NULL,
  `AIRPORT_NAME` varchar(100) DEFAULT NULL,
  `CITY_ID_FK` char(3) DEFAULT NULL,
  PRIMARY KEY (`AIRPORT_ID`),
  KEY `AIRPORTS_AIRPORT_ID_IDX` (`AIRPORT_ID`) USING BTREE,
  KEY `CITY_ID_FK` (`CITY_ID_FK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- DSTAIRLINES.FLIGHT_TIME_STATUS definition

CREATE TABLE `FLIGHT_TIME_STATUS` (
  `FTS_ID` varchar(10) NOT NULL,
  `FTS_DEFINITION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`FTS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- DSTAIRLINES.FLIGHTS_SCHEDULES_PASSENGER definition

CREATE TABLE `FLIGHTS_SCHEDULES_PASSENGER` (
  `FSP_ID` int NOT NULL AUTO_INCREMENT,
  `FSP_AIRLINE_FK` varchar(10) DEFAULT NULL,
  `FSP_FLIGHT_NUMBER` varchar(10) DEFAULT NULL,
  `FSP_DAYS_OF_OPERATIONS_UTC` varchar(10) DEFAULT NULL,
  `FSP_START_DATE_UTC` date DEFAULT NULL,
  `FSP_END_DATE_UTC` date DEFAULT NULL,
  `FSP_DAYS_OF_OPERATIONS_LT` varchar(10) DEFAULT NULL,
  `FSP_START_DATE_LT` date DEFAULT NULL,
  `FSP_END_DATE_LT` date DEFAULT NULL,
  PRIMARY KEY (`FSP_ID`),
  KEY `FLIGHTS_SCHEDULES_PASSENGER_FK` (`FSP_AIRLINE_FK`),
  KEY `idx_fsp_1` (`FSP_AIRLINE_FK`,`FSP_FLIGHT_NUMBER`),
  CONSTRAINT `FLIGHTS_SCHEDULES_PASSENGER_FK` FOREIGN KEY (`FSP_AIRLINE_FK`) REFERENCES `AIRLINES` (`AIRLINE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=85860 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- DSTAIRLINES.FLIGHTS_SCHEDULES_PASSENGER_LEGS definition

CREATE TABLE `FLIGHTS_SCHEDULES_PASSENGER_LEGS` (
  `FSPL_ID` int NOT NULL,
  `FSPL_SEQUENCE_NUMBER` int DEFAULT NULL,
  `FSPL_ORIGIN_AIRPORT_FK` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSPL_DESTINATION_AIRPORT_FK` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSPL_SERVICE_TYPE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSPL_OWNER` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSPL_TYPE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSPL_CONFIGURATION` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSPL_DEPARTURE_TIME_UTC` datetime DEFAULT NULL,
  `FSPL_DEPARTURE_TIME_LT` datetime DEFAULT NULL,
  `FSPL_DEPARTURE_DIFF_TIME_UTC` int DEFAULT NULL,
  `FSPL_DEPARTURE_DIFF_TIME_LT` int DEFAULT NULL,
  `FSPL_ARRIVAL_TIME_UTC` datetime DEFAULT NULL,
  `FSPL_ARRIVAL_TIME_LT` datetime DEFAULT NULL,
  `FSPL_ARRIVAL_DIFF_TIME_UTC` int DEFAULT NULL,
  `FSPL_ARRIVAL_DIFF_TIME_LT` int DEFAULT NULL,
  PRIMARY KEY (`FSPL_ID`),
  KEY `FLIGHTS_SCHEDULES_PASSENGER_LEGS_FK` (`FSPL_ORIGIN_AIRPORT_FK`),
  KEY `FLIGHTS_SCHEDULES_PASSENGER_LEGS_FK_1` (`FSPL_DESTINATION_AIRPORT_FK`),
  KEY `idx_fspl_1` (`FSPL_ORIGIN_AIRPORT_FK`,`FSPL_DESTINATION_AIRPORT_FK`,`FSPL_DEPARTURE_TIME_UTC`),
  CONSTRAINT `FLIGHTS_SCHEDULES_PASSENGER_LEGS_FK` FOREIGN KEY (`FSPL_ORIGIN_AIRPORT_FK`) REFERENCES `AIRPORTS` (`AIRPORT_ID`),
  CONSTRAINT `FLIGHTS_SCHEDULES_PASSENGER_LEGS_FK_1` FOREIGN KEY (`FSPL_DESTINATION_AIRPORT_FK`) REFERENCES `AIRPORTS` (`AIRPORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- DSTAIRLINES.OPERATIONS_FLIGHTS_STATUS definition

CREATE TABLE `OPERATIONS_FLIGHTS_STATUS` (
  `OFS_ID` int NOT NULL AUTO_INCREMENT,
  `OFS_DEPARTURE_AIRPORT_FK` varchar(10) DEFAULT NULL,
  `OFS_DEPARTURE_SCHEDULED_TIME_LT` datetime DEFAULT NULL,
  `OFS_DEPARTURE_SCHEDULED_TIME_UTC` datetime DEFAULT NULL,
  `OFS_DEPARTURE_ACTUAL_TIME_UTC` datetime DEFAULT NULL,
  `OFS_DEPARTURE_ACTUAL_TIME_LT` datetime DEFAULT NULL,
  `OFS_DEPARTURE_FTS_FK` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `OFS_ARRIVAL_AIRPORT_FK` varchar(10) DEFAULT NULL,
  `OFS_ARRIVAL_SCHEDULED_TIME_UTC` datetime DEFAULT NULL,
  `OFS_ARRIVAL_SCHEDULED_TIME_LT` datetime DEFAULT NULL,
  `OFS_ARRIVAL_ACTUAL_TIME_LT` datetime DEFAULT NULL,
  `OFS_ARRIVAL_ACTUAL_TIME_UTC` datetime DEFAULT NULL,
  `OFS_ARRIVAL_FTS_FK` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `OFS_MARKETING_CARRIER_AIRLINE_FK` varchar(10) DEFAULT NULL,
  `OFS_MARKETING_CARRIER_FLIGHT_NUMBER` int DEFAULT NULL,
  `OFS_OPERATING_CARRIER_AIRLINE_FK` varchar(10) DEFAULT NULL,
  `OFS_OPERATING_CARRIER_FLIGHT_NUMBER` int DEFAULT NULL,
  `OFS_AIRCRAFT_FK` varchar(10) DEFAULT NULL,
  `OFS_AIRCRAFT_REGISTRATION` varchar(10) DEFAULT NULL,
  `OFS_FTS_FK` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `OFS_SERVICE_TYPE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`OFS_ID`),
  KEY `idx_ofs_1` (`OFS_DEPARTURE_AIRPORT_FK`,`OFS_ARRIVAL_AIRPORT_FK`,`OFS_DEPARTURE_SCHEDULED_TIME_UTC`,`OFS_OPERATING_CARRIER_AIRLINE_FK`,`OFS_OPERATING_CARRIER_FLIGHT_NUMBER`),
  KEY `OFS_DEPARTURE_FTS_FK` (`OFS_DEPARTURE_FTS_FK`),
  KEY `OFS_ARRIVAL_AIRPORT_FK` (`OFS_ARRIVAL_AIRPORT_FK`),
  KEY `OFS_ARRIVAL_FTS_FK` (`OFS_ARRIVAL_FTS_FK`),
  KEY `OFS_MARKETING_CARRIER_AIRLINE_FK` (`OFS_MARKETING_CARRIER_AIRLINE_FK`),
  KEY `OFS_FTS_FK` (`OFS_FTS_FK`),
  CONSTRAINT `OFS_ARRIVAL_AIRPORT_FK` FOREIGN KEY (`OFS_ARRIVAL_AIRPORT_FK`) REFERENCES `AIRPORTS` (`AIRPORT_ID`),
  CONSTRAINT `OFS_ARRIVAL_FTS_FK` FOREIGN KEY (`OFS_ARRIVAL_FTS_FK`) REFERENCES `FLIGHT_TIME_STATUS` (`FTS_ID`),
  CONSTRAINT `OFS_DEPARTURE_AIRPORT_FK` FOREIGN KEY (`OFS_DEPARTURE_AIRPORT_FK`) REFERENCES `AIRPORTS` (`AIRPORT_ID`),
  CONSTRAINT `OFS_DEPARTURE_FTS_FK` FOREIGN KEY (`OFS_DEPARTURE_FTS_FK`) REFERENCES `FLIGHT_TIME_STATUS` (`FTS_ID`),
  CONSTRAINT `OFS_FTS_FK` FOREIGN KEY (`OFS_FTS_FK`) REFERENCES `FLIGHT_TIME_STATUS` (`FTS_ID`),
  CONSTRAINT `OFS_MARKETING_CARRIER_AIRLINE_FK` FOREIGN KEY (`OFS_MARKETING_CARRIER_AIRLINE_FK`) REFERENCES `AIRLINES` (`AIRLINE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=34678 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


# Alimentation manuelle de la table des statuts des vols (il manque peut-être des codes mais il ne doit y en avoir des dizaines...)
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('CD','Flight Cancelled');
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('DP','Flight Departed');
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('DL','Flight Delayed');
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('FE','Flight Early');
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('LD','Flight Landed');
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('OT','Flight On Time');
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('NA','No Status');
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('NO','No Status');
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('DV','To Define DV');
#Insert into DSTAIRLINES.FLIGHT_TIME_STATUS(FTS_ID, FTS_DEFINITION) values ('NI','Next Information');
#
## Insertion des aéroports manquants, inconnus par le service Lufthansa (afin de pallier le problèmes des clès étrangères
#Insert into DSTAIRLINES.AIRPORTS (AIRPORT_ID,AIRPORT_ICAO,AIRPORT_NAME) values ('DTZ','DTZ','UNKNOWN');
#Insert into DSTAIRLINES.AIRPORTS (AIRPORT_ID,AIRPORT_ICAO,AIRPORT_NAME) values ('MKF','MKF','UNKNOWN');
#Insert into DSTAIRLINES.AIRPORTS (AIRPORT_ID,AIRPORT_ICAO,AIRPORT_NAME) values ('QDU','QDU','UNKNOWN');
#Insert into DSTAIRLINES.AIRPORTS (AIRPORT_ID,AIRPORT_ICAO,AIRPORT_NAME) values ('QKL','QKL','UNKNOWN');
#Insert into DSTAIRLINES.AIRPORTS (AIRPORT_ID,AIRPORT_ICAO,AIRPORT_NAME) values ('XER','XER','UNKNOWN');
#Insert into DSTAIRLINES.AIRPORTS (AIRPORT_ID,AIRPORT_ICAO,AIRPORT_NAME) values ('XIU','XIU','UNKNOWN');
#Insert into DSTAIRLINES.AIRPORTS (AIRPORT_ID,AIRPORT_ICAO,AIRPORT_NAME) values ('ZWS','ZWS','UNKNOWN');

